# This is a basic workflow to help you get started with Actions

name: deploy-powershell

# Controls when the workflow will run
on:
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "SCEPman-Powershell-Install"
  SCEPman-Powershell-Install:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_PROD_SUBSCRIPTION_ID }}
      # Run Powershell post installation script.
      - name: Scepman powershell script
        uses: actions/checkout@v2
      - run: |
          extra-config/scepman.ps1
        shell: pwsh  
